version: "3.3"

services: 
  ftp:
    build:
      context: ./
      dockerfile: Dockerfile_ftp
    ports: 
      - 21:21
    volumes: 
      - ./ftp:/ftp/ftp

  web-file-explorer:
    image: filebrowser/filebrowser
    ports: 
      - 80:80
    volumes: 
      - ./ftp:/srv
